language: generic
dist: trusty
sudo: required

matrix:
  fast_finish: true
  include:
    - env: COQ_VERSION="8.6"      COQ_PACKAGE="coq-8.6"   PPA="ppa:jgross-h/many-coq-versions"
    - env: COQ_VERSION="8.5"      COQ_PACKAGE="coq-8.5"   PPA="ppa:jgross-h/many-coq-versions"
    - env: COQ_VERSION="trunk"    COQ_PACKAGE="coq"       PPA="ppa:jgross-h/coq-trunk-daily"
    - env: COQ_VERSION="v8.6"     COQ_PACKAGE="coq"       PPA="ppa:jgross-h/coq-8.6-daily"
    - env: COQ_VERSION="v8.5"     COQ_PACKAGE="coq"       PPA="ppa:jgross-h/coq-8.5-daily"
  allow_failures:
    - env: COQ_VERSION="trunk"    COQ_PACKAGE="coq"       PPA="ppa:jgross-h/coq-trunk-daily"
    - env: COQ_VERSION="v8.6"     COQ_PACKAGE="coq"       PPA="ppa:jgross-h/coq-8.6-daily"
    - env: COQ_VERSION="v8.5"     COQ_PACKAGE="coq"       PPA="ppa:jgross-h/coq-8.5-daily"

before_install:
  - if [ ! -z "$PPA" ]; then sudo add-apt-repository "$PPA" -y; fi
  - sudo apt-get update -q
  - sudo apt-get install $COQ_PACKAGE -y

script:
  - make Makefile.coq
  - env TIMED=1 make -j2 -f Makefile.coq
